version: '3'

volumes:
  download:


services:
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./application:/app/app/static/application
    ports:
      - 5000:5000